PythonDjango/TeamChatCafe/lunchpoll/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),

    path('user/',   include("authentication.urls"), name="user"),
    path('employee/', include("employee.urls"), name="employee"),
    path('menu/',   include("menu.urls")),
    path('order/',  include("order.urls"), name="order"),
    path('statistics/', statistics, name="statistics"),
    path('menu/', menu, name="menu"),
]

PythonDjango/TeamChatCafe/menu/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', book_form, name='book_insert'),
    path('list/', BookListAll.as_view(), name='list_all'),
    #path('<int:book_id>/', by_id, name='by_id'),
    path('<int:id>/', book_form, name='book_update'),
    path('delete/<int:id>/', book_delete, name='book_delete'),
    path('unordered/', unordered, name='unordered'),
    path('book_list/', BookListSearch.as_view(), name='book_list'),

]

PythonDjango/TeamChatCafe/menu/models.py
from django.db import models, IntegrityError, DataError

from employee.models import Employee

class Menu(models.Model):
    """
        This class represents an employee. \n
        Attributes:
        -----------
        param name: Describes name of the menu
        type name: str max_length=128
        param description: Describes description of the menu
        type description: str
        param count: Describes count of the menu
        type count: int default=10
        param authors: list of Authors
        type authors: list->employee
    """

    name = models.CharField(blank=True, max_length=128)
    description = models.TextField(blank=True)
    count = models.IntegerField(default=10)
    authors = models.ManyToManyField(Employee, related_name='books')

    def __str__(self):
        """
        Magic method is redefined to show all information about Menu.
        :return: menu id, menu name, menu description, menu count, menu authors
        """
        return str(self.to_dict())[1:-1]

    def __repr__(self):
        """
        This magic method is redefined to show class and id of Menu object.
        :return: class, id
        """
        return f'{self.__class__.__name__}(id={self.id})'

    @staticmethod
    def get_by_id(book_id):
        """
        :param book_id: SERIAL: the id of a Menu to be found in the DB
        :return: menu object or None if a menu with such ID does not exist
        """
        try:
            user = Menu.objects.get(pk=book_id)
            return user
        except Menu.DoesNotExist:
            pass
            # LOGGER.error("User does not exist")

    @staticmethod
    def delete_by_id(book_id):
        """
        :param book_id: an id of a menu to be deleted
        :type book_id: int
        :return: True if object existed in the db and was removed or False if it didn't exist
        """

        try:
            menu = Menu.objects.get(id=book_id)
            menu.delete()
            return True
        except Menu.DoesNotExist:
            # LOGGER.error("User does not exist")
            pass
        return False

    @staticmethod
    def create(name, description, count=10, authors=None):
        """
        param name: Describes name of the menu
        type name: str max_length=128
        param description: Describes description of the menu
        type description: str
        param count: Describes count of the menu
        type count: int default=10
        param authors: list of Authors
        type authors: list->employee
        :return: a new menu object which is also written into the DB
        """
        menu = Menu(name=name, description=description, count=count)
        try:
            menu.save()
            if authors is not None:
                for employee in authors:
                    menu.authors.add(employee)
            menu.save()
            return menu
        except (IntegrityError, AttributeError, DataError):
            # LOGGER.error("Wrong attributes or relational integrity error")
            pass

    def to_dict(self):
        """
        :return: menu id, menu name, menu description, menu count, menu authors
        :Example:
        | {
        |   'id': 8,
        |   'name': 'django menu',
        |   'description': 'bla bla bla',
        |   'count': 10',
        |   'authors': []
        | }
        """

        return {
            'id': self.id,
            'name': self.name,
            'description': self.description,
            'count': self.count,
            'authors': [employee.id for employee in self.authors.all()]
        }

    def update(self, name=None, description=None, count=None):
        """
        Updates menu in the database with the specified parameters.\n
        param name: Describes name of the menu
        type name: str max_length=128
        param description: Describes description of the menu
        type description: str
        param count: Describes count of the menu
        type count: int default=10
        :return: None
        """

        if name:
            self.name = name
        if description:
            self.description = description
        if count:
            self.count = count
        self.save()

    def add_authors(self, authors):
        """
        Add  authors to  menu in the database with the specified parameters.\n
        param authors: list authors
        :return: None
        """

        for employee in authors:
            self.authors.add(employee)
        self.save()

    def remove_authors(self, authors):
        """
        Remove authors to  menu in the database with the specified parameters.\n
        param authors: list authors
        :return: None
        """
        for employee in authors:
            self.authors.remove(employee)
        self.save()

    @staticmethod
    def get_all():
        """
        returns data for json request with QuerySet of all books
        """
        all_users = Menu.objects.all()
        return list(all_users)

    @staticmethod
    def get_all_ordered(order_by, filter):
        """
        returns data for json request with QuerySet of filtered and ordered books
        """
        all_books = Menu.objects.filter(**filter).order_by(*order_by)
        return list(all_books)
    
    def all_authors_string(self):
        """
        Returns a list of authors as a string enumeration. 
        """
        autors = [employee.surname_initials() for employee in employee.objects.filter(books__id = self.id)]
        return ", ".join(autors)

PythonDjango/TeamChatCafe/menu/forms.py
from dataclasses import fields
from django import forms
from .models import Menu

class BookForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ('name', 'description', 'count', 'authors')
        labels = {
            'name': 'Назва книги',
            'description': 'Опис',
            'count': 'Кількість',
            'authors': 'Автори',
        }
        
    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        self.fields['description'].required = False
        self.fields['count'].required = False
        

PythonDjango/TeamChatCafe/menu/views.py
from django.shortcuts import render, redirect
from menu.forms import BookForm
from menu.models import Menu
from order.models import Order
from employee.models import Employee
from authentication.models import CustomUser 
from django.db.models import Q
from django.views.generic import ListView

class BookListSearch(ListView):
    
    model = Menu
    template_name = "menu/list_part2.html"
    context_object_name = "books"
  
    def get(self, request, *args, **kwargs):
         
        self.filter  = {}
        self.order_by = []
        self.book_id = ""
        self.book_name = ""
        self.author_id = 0
        self.user_id = 0
        self.name = 'none'
        self.count = 'none'
        self.authors = list(Employee.objects.all())
        self.users = list(CustomUser.objects.all())
        self.book_info = ""
        self.author_info = ""
        self.search_en = False
        self.q_filter = {}
        data = request.GET
        
        if 'author_id' in data and not data['author_id'] == "0":
            self.author_id = int(data['author_id'])
            self.filter['authors__id'] = self.author_id
            
        if 'user_id' in data and not data['user_id'] == "0":
            user_filter = {}
            self.user_id =  int(data['user_id'])
            if 'book_id' in data and not data['book_id'] == "":
                self.book_id =  int(data['book_id'])
                user_filter['book__pk'] = self.book_id
            if 'book_name' in data and not data['book_name'] == "":
                self.book_name = data['book_name']
                user_filter['book__name__icontains'] = self.book_name              
                           
            user_filter['user__pk'] = self.user_id
            user_books_idlist = [order.book_id for order in list(Order.objects.filter(**user_filter))]
            self.filter['id__in'] = user_books_idlist

        if 'search_en' in data and data['search_en'] == 'on':
            self.search_en = data['search_en']
            self.author_info = data['author_info']
            self.book_info = data['book_info']
            self.q_filter = (Q(name__icontains = self.book_info) | \
                             Q(description__icontains = self.book_info)) & \
                            (Q(authors__name__icontains = self.author_info) | \
                             Q(authors__surname__icontains = self.author_info) | \
                             Q(authors__patronymic__icontains = self.author_info) )
        
        else:
            if 'book_id' in data and not data['book_id'] == "":
                self.book_id = data['book_id']
                self.filter['id'] = self.book_id
            if 'book_name' in data and not data['book_name'] == "":
                self.book_name = data['book_name']
                self.filter['name__icontains'] = self.book_name
                   
        if 'name' in data and not data['name'] == 'none':
            self.name = data['name']
            self.order_by.append('name' if self.name == 'asc' else '-name')
        
        if 'count' in data and not data['count'] == 'none':
            self.count = data['count']
            self.order_by.append('count' if self.count == 'asc' else '-count')     
              
        return ListView.get(self, request, *args, **kwargs)  

    def get_context_data(self, **kwargs):
      
        context = super(BookListSearch, self).get_context_data(**kwargs)
        context['title'] = 'Список книг'
        context['content_title'] = 'Адміністрування бібліотеки / Розширений пошук'
        context['authors'] = self.authors
        context['users'] = self.users
        context['orders_by'] = {'name': self.name, 'count': self.count}
        context['filters'] = {
                                'book_id': self.book_id,
                                'book_name': self.book_name, 
                                'author_id': self.author_id, 
                                'user_id': self.user_id
                                }

        context['search_param'] = {
                                'author_info': self.author_info,
                                'book_info': self.book_info,
                            }
        context['search_en'] = self.search_en
   
        return context
   
    def get_queryset(self):
        
        if self.search_en == 'on':
            queryset = Menu.objects.filter(self.q_filter).distinct()
        else:
            queryset = Menu.get_all_ordered(self.order_by, self.filter)

        return queryset  

class BookListAll(ListView):
    
    model = Menu
    template_name = "menu/book_list.html"
    context_object_name = "books"
  
    def get_context_data(self, **kwargs):
      
        context = super(BookListAll, self).get_context_data(**kwargs)
        context['title'] = 'Menu'
        context['content_title'] = 'List of new dish'
   
        return context
   
    def get_queryset(self):
        
        queryset = Menu.get_all()

        return queryset  

def book_form(request, id):
    if request.method == "GET":
        if id:
            book_by_id = Menu.get_by_id(id)
            form = BookForm(instance = book_by_id) 
        else:
            form = BookForm()
        return render(request, 'menu/book_by_id.html', {'form': form}) 
    else:   
        if id:
            book_by_id = Menu.get_by_id(id)
            form = BookForm(request.POST, instance = book_by_id) 
        else:
            form = BookForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('book_list')   
    
def book_delete(request, id):
    book_by_id = Menu.get_by_id(id)
    book_by_id.delete()
    return redirect('book_list')        


def by_id(request, book_id): # canceled

    book_by_id = Menu.get_by_id(book_id)
    context = { 'title': 'Детальна інформація',
                'content_title': 'Адміністрування бібліотеки / Детальна інформація',
                'content': book_by_id
              }
    if book_by_id:
        return render(request, 'menu/book_by_id.html', context)
    else:
        return redirect('menu/list')

def unordered(request):
    
    unordered_books = Menu.objects.exclude(id__in = Order.objects.values_list('book_id'))
    context = {}
    context['title'] = 'Список читачів'
    context['content_title'] = 'Адміністрування бібліотеки / Доступні книжки'
    context['books'] = unordered_books

    return render(request, 'menu/book_list.html', context)

PythonDjango/TeamChatCafe/templates/_base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">

    {% block title %}  
       
    {% endblock title%}
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>

<body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}"></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <li><a class="nav-link" href="{% url 'user_create' %}">Create User</a></li>
            </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'menu' %}">Menu</a>
              </li> 
              <li class="nav-item dropdown">
{#                <a class="nav-link" href="{% url 'щквук' %}">#}
                    <a class="nav-link dropdown-toggle" href="{% url 'order_list' %}" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Order
                    </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
{#                    <li><a class="nav-link" href="{% url 'order_list' %}">Замовлення</a></li>#}
                    <li><a class="dropdown-item" href="{% url 'order_create' %}">Create Order</a></li>
                    <li><a class="dropdown-item" href="{% url 'order_list' %}">List of orders+</a></li>
                </ul>
              </li>            
              <li class="nav-item dropdown">
{#                <a class="nav-link" href="{% url 'employee' %}">#}
                    <a class="nav-link dropdown-toggle" href="{% url 'author_list' %}" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Employee
                    </a>
                 <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
{#                    <li><a class="dropdown-item" href="{% url 'employee' %}">Список авторів</a></li>#}
                    <li><a class="dropdown-item" href="{% url 'author_create' %}">Creating employee</a></li>
                    <li><a class="dropdown-item" href="{% url 'author_list' %}">Creating of employee +</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Create Menu
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'list_all' %}">List of dish </a></li>
                  {% comment %} <li><a class="dropdown-item" href="{% url 'menu_list' %}">Shearch dish </a></li> {% endcomment %}
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'menu' %}">Polls</a>
              </li> 
            </ul>
          </div>
        </div>
      </nav>

    {% block header %}

    {% endblock header%}

    {% block content %}

    {% endblock %}

        </div>
        <!-- Copyright -->
      </footer>

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
      </body>

</html>

PythonDjango/TeamChatCafe/templates/index.html
{% extends '_base.html' %}

{% block title %}
       
<title>{{ title }}</title>

{% endblock title%}

{% block header %}

<h1> {{header}} </h1>

{% endblock header %}

{% block content %}

<div align = 'center'>
    <div >
		<h1>{{content_title}}</h1>
	</div>
</div>

{{content}}

<p></p>



{% endblock %}

PythonDjango/TeamChatCafe/templates/menu.html
{% extends '_base.html' %}

{% block content %}

<div align = 'center'>
  <div >
    <h1>{{content_title}}</h1>
  </div>
</div>
<h1> Main Dish </h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Dish</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td>Borsch</td>
      </tr>
      <tr>
        <th scope="row">2</th>
        <td>Pizza</td>
      </tr>
      <tr>
        <th scope="row">3</th>
        <td>Spaghetti</td>
      </tr>
      <tr>
        <th scope="row">4</th>
        <td>Salade</td>
      </tr>
    </tbody>
  </table>
  <br>
  <h1> Dessert </h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Dessert</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td>Trifle</td>
      </tr>
      <tr>
        <th scope="row">2</th>
        <td>Cheescake</td>
      </tr>
      <tr>
        <th scope="row">3</th>
        <td>Pie</td>
      </tr>
      <tr>
        <th scope="row">4</th>
        <td>Donats</td>
      </tr>
    </tbody>
  </table>
  <br>
  <h1> Water </h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Drinks</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td>Coke</td>
      </tr>
      <tr>
        <th scope="row">2</th>
        <td>Sprite</td>
      </tr>
      <tr>
        <th scope="row">3</th>
        <td>Wine</td>
      </tr>
      <tr>
        <th scope="row">4</th>
        <td>Fanta</td>
      </tr>
      <tr>
        <th scope="row">4</th>
        <td>Juice</td>
      </tr>
    </tbody>
  </table>
  <br>
  <a href="{% url 'index' %}">Back</a>
{% endblock content %}